version: "2.2"
services: 
  elasticsearch761:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      # - node.name:es01
      # - cluster.name:es-docker-cluster
      # - cluster.initial_master_nodes:es01
      # - bootstrap.memory_lock:true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
