spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_base?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers
mybatis-plus:
  mapper-locations: classpath:mappers