version: "2"
services:
  postgres9:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5433:5432
    volumes: 
      - ./data:/var/lib/postgresql/data
    privileged: true
    
