server:
  port: 8080

spring:
  application:
    name: spring-cloud-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/
zuul:
  routes:
    spring-cloud-client-01:
      path: /client/01/**
      serviceId: spring-cloud-client-01