server:
  port: 8083

spring:
  application:
    name: spring-cloud-client-01
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/