spring:
  profiles:
    active: dbcommons
logging:
  level:
    com.example.commons.db.mybatis.plus.pagehelper.test: debug
mybatis:
  mapper-locations: classpath*:mappers/*.xml
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml