version: "2"
services: 
  vsftpd:
    container_name: vsftpd
    image: fauria/vsftpd
    ports: 
      - 20:20
      - 21:21
      - 21100-21110:21100-21110
    volumes: 
      - ./data:/home/vsftpd
    privileged: true
    environment: 
      - FTP_USER=root
      - FTP_PASS=root