spring:
  application:
    name: eurka-server
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/
#      defaultZone: http://localhost:10001/eureka/
server:
  port: 10001
