
spring:
  application:
    name: eurka-server-01
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
server:
  port: 10001
