server:
  port: 9000

spring:
  profiles:
    active: native
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuan50697105/my-admin-test
          search-paths: properties
          default-label: master
      discovery:
        service-id: ${spring.application.name}
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/