server:
  port: 9000

spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/**
        bootstrap: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/