spring:
  elasticsearch:
    rest:
      uris: 123.56.78.153:9200
  data:
    elasticsearch:
      properties:
        path:
          home: target/elastic
        transport:
          tcp:
            connect_timeout: 120s