version: "2"
networks: 
  mysql:
services: 
  mysql57:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    networks: 
      - mysql
    restart: always
    privileged: true