version: "2"
networks: 
  spring_boot_app:
    name: spring_boot_app
    driver: bridge
services: 
  mysql80:
    image: mysql:8.0
    container_name: spring_boot_app_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    restart: always
    privileged: true
    networks: 
      - spring_boot_app