version: "2"
services: 
  spring_boot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports: 
      - 8101:8081
<<<<<<< HEAD
    networks: 
      - spring_boot_app
=======
    depends_on: 
      - mysql80
    links: 
      - mysql80:mysql
  mysql80:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_01
    restart: always
    privileged: true
>>>>>>> 455ae2b438a6ce21a7edb1eda31e8c9c74c0339c
