-- auto Generated on 2020-04-11
DROP TABLE IF EXISTS customer_type;
CREATE TABLE customer_type(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	create_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '编号',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '名称',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'customer_type';
