version: '2'
services:
  mongo4:
    image: mongo:4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports: 
      - 27017:27017
    volumes: 
      - ./data:/data/db
    restart: always
    privileged: true
