version: "2"
networks:
  app:
    name: app
    driver: brige
services:
  vue_app:
    container_name: vue_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app
