spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///demo_java_01?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    initialize-schema: embedded