version: "2"
networks: 
  shower:
services: 
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80
    links: 
      - tomcat
      - tomcat-admin
      - tomcat-wx
      - tomcat-device
    networks: 
      - shower
  tomcat:    
    image: tomcat:9-jre8
    # ports: 
      # - 8081:8080
    volumes: 
      - /root/tomcat/tomcat9/webapps:/usr/local/tomcat/webapps
      - /root/tomcat/tomcat9/logs:/usr/local/tomcat/logs
    networks: 
      - shower
  tomcat-admin:    
    image: tomcat:9-jre8
    # ports: 
      # - 8082:8080
    volumes: 
      - /root/tomcat/tomcat9/admin/webapps:/usr/local/tomcat/webapps
      - /root/tomcat/tomcat9/logs:/usr/local/tomcat/logs 
    networks: 
      - shower
  tomcat-wx:    
    image: tomcat:9-jre8
    # ports: 
      # - 8083:8080
    volumes: 
      - /root/tomcat/tomcat9/wx/webapps:/usr/local/tomcat/webapps
      - /root/tomcat/tomcat9/logs:/usr/local/tomcat/logs 
    networks: 
      - shower
  tomcat-device:    
    image: tomcat:9-jre8
    # ports: 
      # - 8084:8080
    volumes: 
      - /root/tomcat/tomcat9/wx/webapps:/usr/local/tomcat/webapps
      - /root/tomcat/tomcat9/logs:/usr/local/tomcat/logs 
    networks: 
      - shower