spring:
  profiles:
    active: dbcomons
  data:
    jest:
      uris: http://123.56.78.153:9200
      username: elastic
      password: changeme
#    elasticsearch:
#      properties:
#        path:
#          home: target/elastic
#        transport:
#          tcp:
#            connect_timeout: 120s